{{ if index .Values "eric-lcm-container-registry" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-app-mgr.lcmregistry" . }}
  labels:
    {{- include "eric-oss-app-mgr.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-app-mgr.helm-annotations" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ include "eric-oss-app-mgr.lcmregistrycred" . }}
  name: {{ index .Values "eric-lcm-container-registry" "registry" "users" "name" | b64enc }}
  password: {{ index  .Values "eric-lcm-container-registry" "registry" "users" "password" | b64enc }}
{{- end -}}