#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
{{- if .Values.global.iccrAppIngresses }}
{{- if .Values.ingress.enabled -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mgr-ingress-iccr
  labels:
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
  annotations:
{{- if .Values.global.ingressClass }}
    {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
    kubernetes.io/ingress.class: {{.Values.global.ingressClass | quote }}
{{- end }}
spec:
  virtualhost:
    fqdn: {{ required "A valid .Values.global.hosts.appmgr entry required" .Values.global.hosts.appmgr }}
{{- if .Values.ingress.tls.enabled }}
    tls:
      secretName: {{ required "A valid .Values.ingress.tls.secretName entry required" .Values.ingress.tls.secretName | quote }}
{{- end }}
  routes:
  - conditions:
    - prefix: /
    services:
    - name: eric-eo-api-gateway
      port: 80
    timeoutPolicy:
      response: "300s"
{{- end }}
{{- end }}
