apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-sa
  labels:
    app: {{ template "eric-oss-app-mgr.name" . }}
    chart: {{ template "eric-oss-app-mgr.chart" . }}
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
automountServiceAccountToken: false
