#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
{{ if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-registry-policy
  labels:
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: eric-data-object-storage-mn
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: eric-data-object-storage-mn
    - podSelector:
        matchLabels:
          app: eric-lcm-helm-chart-registry
    - podSelector:
        matchLabels:
          app: eric-pm-server
    - podSelector:
        matchLabels:
          app: eric-lcm-container-registry
    - podSelector:
        matchLabels:
          app: eric-data-object-storage-mn-bragent
{{- end }}