#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
{{ if .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-bragent-policy
  labels:
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: eric-appmgr-data-document-db-bragent
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: eric-appmgr-data-document-db
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: eric-ctrl-bro
    ports:
    - protocol: TCP
      port: 8083
{{- end }}