apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-{{ template "eric-oss-app-mgr.privileged.cluster.role.name" . }}-psp-binding
  labels:
    app: {{ template "eric-oss-app-mgr.name" . }}
    chart: {{ template "eric-oss-app-mgr.chart" . }}
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-oss-app-mgr.privileged.cluster.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-oss-app-mgr.name" . }}-sa