#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $serviceMesh := include "eric-oss-app-mgr.service-mesh.enabled" . | trim }}
{{ $tls := include "eric-oss-app-mgr.global-security-tls-enabled" . | trim }}
{{ if and (eq $serviceMesh "true") (eq $tls "true") }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-eric-oss-app-onboarding-destinationrule
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
  labels:
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
spec:
  exportTo:
  - "."
  host: eric-oss-app-onboarding
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "connectionPool" "http1MaxPendingRequests" }}
        http2MaxRequests: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "connectionPool" "http2MaxRequests" }}
        maxRequestsPerConnection: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "connectionPool" "maxRequestsPerConnection" }}
      tcp:
        maxConnections: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "connectionPool" "maxConnections" }}
    outlierDetection:
      baseEjectionTime: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "outlierDetection" "baseEjectionTime" }}
      consecutive5xxErrors: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "outlierDetection" "consecutive5xxErrors" }}
      interval: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "outlierDetection" "interval" }}
      maxEjectionPercent: {{ index .Values "eric-oss-app-onboarding" "destinationRule-config" "outlierDetection" "maxEjectionPercent" }}
{{- end -}}
