#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $serviceMesh := include "eric-oss-app-mgr.service-mesh.enabled" . | trim }}
{{ $tls := include "eric-oss-app-mgr.global-security-tls-enabled" . | trim }}
{{ if and (eq $serviceMesh "true") (eq $tls "true") }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-acm-runtime-kafka-broker-destinationrule
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
  labels:
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
spec:
  exportTo:
  - "."
  host: eric-oss-dmm-kf-op-sz-kafka-brokers
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 9093
      tls:
        mode: MUTUAL
        clientCertificate: /etc/istio/tls/eric-oss-dmm-kf-op-sz/cert.pem
        privateKey: /etc/istio/tls/eric-oss-dmm-kf-op-sz/key.pem
        caCertificates: /etc/istio/tls-ca/cacertbundle.pem
  workloadSelector:
    matchLabels:
      eric-oss-dmm-kf-op-sz-ism-access: "true"
{{- end }}
