{{- $useCertMOnboarding := include "eric-oss-app-mgr.certm-onboarding.enabled" . | trim -}}
{{- if eq $useCertMOnboarding "true" -}}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-asymmetric-cert
  labels:
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
spec:
  generated-secret-name: {{ .Values.ingress.tls.secretName }}
  generated-secret-type: tls
  asymmetric-key-certificate-name: appmgr-http-server/appmgr-http-server
{{- end -}}