#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if index .Values "eric-oss-acm-runtime" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-oss-app-mgr.name" . }}-acm-runtime-db-secret
  labels:
  {{- include "eric-oss-app-mgr.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-app-mgr.helm-annotations" .| nindent 4 }}
data:
  login: {{ include "eric-oss-app-mgr.acm-runtime-db-username" . }}
  password: {{ include "eric-oss-app-mgr.acm-runtime-db-password" . }}
{{- end -}}